/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import br.com.cis.sdk.CisBiox;
import com.sun.jna.Memory;
import com.sun.jna.Pointer;
import com.sun.jna.ptr.IntByReference;
import com.sun.jna.ptr.PointerByReference;
import dao.DigitalDAO;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Digital;

/**
 *
 * @author Samuelson
 */
public class ViewBuscar extends javax.swing.JFrame {

    /**
     * Creates new form ViewComparar
     */
    public ViewBuscar() {
        initComponents();

    }

    private Runnable LerDigital = new Runnable() {
        public void run() {
            try {
                // Instanciar a DLL
                CisBiox biox = new CisBiox();

                // Capturar a digital no leitor   
                Pointer pDigital;
                IntByReference iRet = new IntByReference();
                pDigital = biox.lerDigital_RetornoPonteiro(iRet);
                int iRetorno2 = iRet.getValue();
                if (iRetorno2 != 1) {
                    biox.finalizar();
                    return;
                }
                byte[] buffer = pDigital.getByteArray(0, 669);

                DigitalDAO dao = new DigitalDAO();
                Digital d = new Digital();

                for (Digital dd : dao.read()) {

                    final Pointer p1 = new Memory(669);
                    p1.write(0, buffer, 0, buffer.length);
                    final PointerByReference pr1 = new PointerByReference();
                    pr1.setPointer(p1);

                    Pointer p2 = new Memory(669);
                    p2.write(0, dd.getDigital1(), 0, dd.getDigital1().length);
                    PointerByReference pr2 = new PointerByReference();
                    pr2.setPointer(p2);

                    // Comparar as duas digitais
                    int iRetorno = biox.CIS_SDK_Biometrico_CompararDigital(pr1, pr2);

                    switch (iRetorno) {
                        case 1:
//                            JOptionPane.showMessageDialog(null, "As digitais são iguais");
                            txtNome.setText(dd.getNome());
                            break;
                        case -2:
                            JOptionPane.showMessageDialog(null, "As digitais são diferentes");
                            break;
                        default:
                            JOptionPane.showMessageDialog(null, "Erro: " + Integer.toString(iRetorno));
                            break;
                    }

                }

                d.setDigital1(buffer);

            } catch (HeadlessException | SQLException e) {
                System.out.println(e);
            } catch (Exception ex) {
                Logger.getLogger(ViewBuscar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    ;

    };
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Buscar por Biometria ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jButton1)
                .addGap(40, 40, 40)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CisBiox biox = new CisBiox();

        if (biox.iniciar() != 1) {
            JOptionPane.showMessageDialog(null, "Erro: "+biox.iniciar());
        }
        new Thread(LerDigital).start();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBuscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
